# Generated by Django 3.1.6 on 2021-05-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogers', '0006_auto_20210509_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=20)),
                ('blog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogers.blogmodel')),
            ],
        ),
    ]
